CREATE TABLE TAR00300_TAR_Tenant_MSTR (
    OTVTAR_Tenant_Status      SMALLINT,
    OTVTAR_Program_ID         CHAR(15)     NOT NULL,
    OTVTAR_Tenant_ID          CHAR(11)     NOT NULL,
    OTVTAR_App_Last_Name      CHAR(21),
    OTVTAR_App_First_Name     CHAR(21),
    OTVTAR_App_Middle_Name    CHAR(21),
    OTVTAR_Cur_Name           CHAR(31),
    OTVTAR_Cur_Address1       CHAR(31),
    OTVTAR_Cur_Address2       CHAR(31),
    OTVTAR_Cur_City           CHAR(21),
    OTVTAR_Cur_CountyCode     CHAR(3),
    OTVTAR_Cur_State          CHAR(3),
    OTVTAR_Cur_ZipCode        CHAR(11),
    OTVTAR_Cur_Telephone      CHAR(11),
    OTVTAR_Perm_Name          CHAR(31),
    OTVTAR_Perm_Address1      CHAR(31),
    OTVTAR_Perm_Address2      CHAR(31),
    OTVTAR_Perm_City          CHAR(21),
    OTVTAR_Perm_State         CHAR(3),
    OTVTAR_Perm_ZipCode       CHAR(11),
    OTVTAR_Perm_Telephone     CHAR(11),
    OTVTAR_Sex                SMALLINT,
    OTVTAR_Project_ID         CHAR(15),
    OTVTAR_Fam_Minority_Code  SMALLINT,
    OTVTAR_Tribal_Code        CHAR(3),
    OTVTAR_Birth_Date         DATETIME,
    OTVTAR_Elderly            TINYINT,
    OTVTAR_Disabled           TINYINT,
    OTVTAR_Handicapped        TINYINT,
    OTVTAR_HusbWife           TINYINT,
    OTVTAR_Family_Count       SMALLINT,
    OTVTAR_Bedrooms           SMALLINT,
    OTVTAR_DIB                CHAR(7),
    OTVTAR_Marital_Status     SMALLINT,
    OTVTAR_Dependent_Count    SMALLINT,
    OTVTAR_VANumber           CHAR(11),
    OTVTAR_Benefit_SSN        CHAR(11),
    OTVTAR_Wages              TINYINT,
    OTVTAR_Benefits_SS        TINYINT,
    OTVTAR_Benefits_SSI       TINYINT,
    OTVTAR_Benefits_VA        TINYINT,
    OTVTAR_Benefits_Other     TINYINT,
    OTVTAR_Welfare_AFDC       TINYINT,
    OTVTAR_Welfare_OAA        TINYINT,
    OTVTAR_Welfare_AD         TINYINT,
    OTVTAR_Welfare_Other      TINYINT,
    OTVTAR_Other_Income       TINYINT,
    OTVTAR_Gross_Income       INT,
    OTVTAR_Adj_Gross_Income   INT,
    OTVTAR_Anticipated_Rent   INT,
    OTVTAR_Recert_Date        DATETIME,
    OTVTAR_Empr_Name          CHAR(31),
    OTVTAR_Empr_Address1      CHAR(31),
    OTVTAR_Empr_Address2      CHAR(31),
    OTVTAR_Empr_City          CHAR(21),
    OTVTAR_Empr_State         CHAR(3),
    OTVTAR_Empr_ZipCode       CHAR(11),
    OTVTAR_Empr_Telephone     CHAR(11),
    OTVTAR_Housing_Code       SMALLINT,
    OTVTAR_Housing_Cost       INT,
    OTVTAR_Displacement_Stat  SMALLINT,
    OTVTAR_Credit_Verified    TINYINT,
    OTVTAR_Total_Assets       INT,
    OTVTAR_Previous_Aid       TINYINT,
    OTVTAR_Owner_ID           CHAR(15),
    OTVTAR_Unit_ID            CHAR(15),
    OTVTAR_Lease_Date         DATETIME,
    OTVTAR_Security_Deposit   INT,
    OTVTAR_Rent_Amount        INT,
    OTVTAR_Number_Incomes     SMALLINT,
    OTVTAR_Income_From_Asset  INT,
    OTVTAR_Qualify_Low_Income  INT,
    OTVTAR_Qualify_VeryLow_Income  INT,
    OTVTAR_Low_Income_Code    TINYINT,
    OTVTAR_VeryLow_Income_Co  TINYINT,
    OTVTAR_MedAllowance_Amt   INT,
    OTVTAR_TotalAllow_Amt     INT,
    OTVTAR_Gross_Rent         INT,
    OTVTAR_GrossRent_Cont     INT,
    OTVTAR_HAP_Amt            INT,
    OTVTAR_UtilitiesAllow_Am  INT,
    OTVTAR_Net_Rent_Cont      INT,
    OTVTAR_Cerficate_Number   SMALLINT,
    OTVTAR_Movein_Date        DATETIME,
    OTVTAR_Moveout_Date       DATETIME,
    OTVTAR_Enumeration_Code   CHAR(3),
    OTVTAR_Claim_Amt          NUMERIC(18,2),
    OTVTAR_PrefPayment_Date   DATETIME,
    OTVTAR_LeaseSublease      CHAR(1),
    OTVTAR_LeaseSublease_Dat  DATETIME,
    OTVTAR_AR_Balance         NUMERIC(18,2),
    OTVTAR_Next_Number        SMALLINT,
    OTVTAR_YTDUtilityAllow_A  NUMERIC(18,2),
    OTVTAR_Admin_Fee          NUMERIC(18,2),
    OTVTAR_Last_Number        INT,
    OTVTAR_Contract_Number    CHAR(17),
    OTVTAR_Security_Deposit_  NUMERIC(18,2),
    OTVTAR_HAP_Payment_Code   CHAR(1),
    OTVTAR_Terminated_Status  CHAR(1),
    OTVTAR_Sec8_Ref_Number    SMALLINT,
    OTVTAR_WO_Pending         TINYINT,
    OTVTAR_WO_Amount          NUMERIC(18,2),
    OTVTAR_Security_Refund    TINYINT,
    OTVTAR_SecurityCheckNO    INT,
    OTVTAR_ChargeOƯ_Date      DATETIME,
    OTVTAR_Collection_Expens  NUMERIC(18,2),
    OTVTAR_Collection_Amount  NUMERIC(18,2),
    OTVTAR_Collection_Orig_A  NUMERIC(18,2),
    OTVTAR_RecChg_Flag        TINYINT,
    OTVTAR_RecChg_Amount      INT,
    OTVTAR_RecChg_Acct_1      CHAR(5),
    OTVTAR_RecChg_Acct_2      CHAR(5),
    OTVTAR_RecChg_Acct_3      CHAR(5),
    OTVTAR_RecChg_Acct_4      CHAR(5),
    OTVTAR_RecChg_Acct_5      CHAR(5),
    OTVTAR_RecChg_Desc        CHAR(31),
    OTVTAR_Lagoon_Flag        TINYINT,
    OTVTAR_Lagoon_Amount      NUMERIC(18,2),
    OTVTAR_Lawn_Flag          TINYINT,
    OTVTAR_Lawn_Amount        NUMERIC(18,2),
    OTVTAR_Rent_Change_Date   DATETIME,
    OTVTAR_Water_Flag         TINYINT,
    OTVTAR_Water_Amount       NUMERIC(18,2),
    OTVTAR_Accept_Pay_Type    SMALLINT,
    OTVTAR_ACH_AccountNumber  CHAR(21),
    OTVTAR_ACH_BankName       CHAR(31),
    OTVTAR_ACH_Checkbox       TINYINT,
    OTVTAR_ACH_EnrollDate     DATETIME,
    OTVTAR_ACH_RentAmount     NUMERIC(18,2),
    OTVTAR_ACH_RoutingNumber  CHAR(17),
    OTVTAR_ACH_StartDate      DATETIME,
    NOTEINDX                  NUMERIC(18,2),
    OTVTAR_Maintenance_Amt    NUMERIC(18,2),
    OTVTAR_Payment_Agreement  TINYINT,
    OTVTAR_Agreement_Desc     CHAR(31),
    OTVTAR_Veteran            TINYINT,
    OTVTAR_Elig_Income        INT,
    OTVTAR_DC_Number          INT,
    DEX_ROW_ID                INT,
    CONSTRAINT PK_TAR_Tenant_MSTR PRIMARY KEY CLUSTERED (OTVTAR_Program_ID, OTVTAR_Tenant_ID)
);

-- CREATE INDEX UNIQUE
CREATE UNIQUE INDEX UX_TAR_Tenant_MSTR_Unique
ON TAR00300_TAR_Tenant_MSTR (OTVTAR_Program_ID, OTVTAR_Tenant_ID, OTVTAR_App_Last_Name, OTVTAR_App_First_Name, OTVTAR_App_Middle_Name);
GO

-- INDEX NOT CLUSTERED
CREATE NONCLUSTERED INDEX IX_TAR00201_Program_ID
ON TAR00300_TAR_Tenant_MSTR (OTVTAR_Program_ID);
GO
-- INDEX NOT CLUSTERED
CREATE NONCLUSTERED INDEX IX_TAR00201_Tenant_ID
ON TAR00300_TAR_Tenant_MSTR (OTVTAR_Tenant_ID);
GO
-- INDEX NOT CLUSTERED
CREATE NONCLUSTERED INDEX IX_TAR00201_MiddleName
ON TAR00300_TAR_Tenant_MSTR (OTVTAR_App_Middle_Name);

-- INDEX NOT CLUSTERED
CREATE NONCLUSTERED INDEX IX_TAR00201_FirstName
ON TAR00300_TAR_Tenant_MSTR (OTVTAR_App_First_Name);
GO
-- INDEX NOT CLUSTERED
CREATE NONCLUSTERED INDEX IX_TAR00201_App_Last_Name
ON TAR00300_TAR_Tenant_MSTR (OTVTAR_App_Last_Name);
GO

CREATE PROCEDURE sp_Insert_TAR_Tenant
(
    @OTVTAR_Tenant_Status SMALLINT,
    @OTVTAR_Program_ID CHAR(15),
    @OTVTAR_Tenant_ID CHAR(11),
    @OTVTAR_App_Last_Name CHAR(21),
    @OTVTAR_App_First_Name CHAR(21),
    @OTVTAR_App_Middle_Name CHAR(21),
    @OTVTAR_Cur_Name CHAR(31),
    @OTVTAR_Cur_Address1 CHAR(31),
    @OTVTAR_Cur_Address2 CHAR(31),
    @OTVTAR_Cur_City CHAR(21),
    @OTVTAR_Cur_CountyCode CHAR(3),
    @OTVTAR_Cur_State CHAR(3),
    @OTVTAR_Cur_ZipCode CHAR(11),
    @OTVTAR_Cur_Telephone CHAR(11),
    @OTVTAR_Perm_Name CHAR(31),
    @OTVTAR_Perm_Address1 CHAR(31),
    @OTVTAR_Perm_Address2 CHAR(31),
    @OTVTAR_Perm_City CHAR(21),
    @OTVTAR_Perm_State CHAR(3),
    @OTVTAR_Perm_ZipCode CHAR(11),
    @OTVTAR_Perm_Telephone CHAR(11),
    @OTVTAR_Sex SMALLINT,
    @OTVTAR_Project_ID CHAR(15),
    @OTVTAR_Fam_Minority_Code SMALLINT,
    @OTVTAR_Tribal_Code CHAR(3),
    @OTVTAR_Birth_Date DATETIME,
    @OTVTAR_Elderly TINYINT,
    @OTVTAR_Disabled TINYINT,
    @OTVTAR_Handicapped TINYINT,
    @OTVTAR_HusbWife TINYINT,
    @OTVTAR_Family_Count SMALLINT,
    @OTVTAR_Bedrooms SMALLINT,
    @OTVTAR_DIB CHAR(7),
    @OTVTAR_Marital_Status SMALLINT,
    @OTVTAR_Dependent_Count SMALLINT,
    @OTVTAR_VANumber CHAR(11),
    @OTVTAR_Benefit_SSN CHAR(11),
    @OTVTAR_Wages TINYINT,
    @OTVTAR_Benefits_SS TINYINT,
    @OTVTAR_Benefits_SSI TINYINT,
    @OTVTAR_Benefits_VA TINYINT,
    @OTVTAR_Benefits_Other TINYINT,
    @OTVTAR_Welfare_AFDC TINYINT,
    @OTVTAR_Welfare_OAA TINYINT,
    @OTVTAR_Welfare_AD TINYINT,
    @OTVTAR_Welfare_Other TINYINT,
    @OTVTAR_Other_Income TINYINT,
    @OTVTAR_Gross_Income INT,
    @OTVTAR_Adj_Gross_Income INT,
    @OTVTAR_Anticipated_Rent INT,
    @OTVTAR_Recert_Date DATETIME,
    @OTVTAR_Empr_Name CHAR(31),
    @OTVTAR_Empr_Address1 CHAR(31),
    @OTVTAR_Empr_Address2 CHAR(31),
    @OTVTAR_Empr_City CHAR(21),
    @OTVTAR_Empr_State CHAR(3),
    @OTVTAR_Empr_ZipCode CHAR(11),
    @OTVTAR_Empr_Telephone CHAR(11),
    @OTVTAR_Housing_Code SMALLINT,
    @OTVTAR_Housing_Cost INT,
    @OTVTAR_Displacement_Stat SMALLINT,
    @OTVTAR_Credit_Verified TINYINT,
    @OTVTAR_Total_Assets INT,
    @OTVTAR_Previous_Aid TINYINT,
    @OTVTAR_Owner_ID CHAR(15),
    @OTVTAR_Unit_ID CHAR(15),
    @OTVTAR_Lease_Date DATETIME,
    @OTVTAR_Security_Deposit INT,
    @OTVTAR_Rent_Amount INT,
    @OTVTAR_Number_Incomes SMALLINT,
    @OTVTAR_Income_From_Asset INT,
    @OTVTAR_Qualify_Low_Income INT,
    @OTVTAR_Qualify_VeryLow_Income INT,
    @OTVTAR_Low_Income_Code TINYINT,
    @OTVTAR_VeryLow_Income_Co TINYINT,
    @OTVTAR_MedAllowance_Amt INT,
    @OTVTAR_TotalAllow_Amt INT,
    @OTVTAR_Gross_Rent INT,
    @OTVTAR_GrossRent_Cont INT,
    @OTVTAR_HAP_Amt INT,
    @OTVTAR_UtilitiesAllow_Am INT,
    @OTVTAR_Net_Rent_Cont INT,
    @OTVTAR_Cerficate_Number SMALLINT,
    @OTVTAR_Movein_Date DATETIME,
    @OTVTAR_Moveout_Date DATETIME,
    @OTVTAR_Enumeration_Code CHAR(3),
    @OTVTAR_Claim_Amt NUMERIC(18,2),
    @OTVTAR_PrefPayment_Date DATETIME,
    @OTVTAR_LeaseSublease CHAR(1),
    @OTVTAR_LeaseSublease_Dat DATETIME,
    @OTVTAR_AR_Balance NUMERIC(18,2),
    @OTVTAR_Next_Number SMALLINT,
    @OTVTAR_YTDUtilityAllow_A NUMERIC(18,2),
    @OTVTAR_Admin_Fee NUMERIC(18,2),
    @OTVTAR_Last_Number INT,
    @OTVTAR_Contract_Number CHAR(17),
    @OTVTAR_Security_Deposit_ NUMERIC(18,2),
    @OTVTAR_HAP_Payment_Code CHAR(1),
    @OTVTAR_Terminated_Status CHAR(1),
    @OTVTAR_Sec8_Ref_Number SMALLINT,
    @OTVTAR_WO_Pending TINYINT,
    @OTVTAR_WO_Amount NUMERIC(18,2),
    @OTVTAR_Security_Refund TINYINT,
    @OTVTAR_SecurityCheckNO INT,
    @OTVTAR_ChargeOut_Date DATETIME,
    @OTVTAR_Collection_Expens NUMERIC(18,2),
    @OTVTAR_Collection_Amount NUMERIC(18,2),
    @OTVTAR_Collection_Orig_A NUMERIC(18,2),
    @OTVTAR_RecChg_Flag TINYINT,
    @OTVTAR_RecChg_Amount INT,
    @OTVTAR_RecChg_Acct_1 CHAR(5),
    @OTVTAR_RecChg_Acct_2 CHAR(5),
    @OTVTAR_RecChg_Acct_3 CHAR(5),
    @OTVTAR_RecChg_Acct_4 CHAR(5),
    @OTVTAR_RecChg_Acct_5 CHAR(5),
    @OTVTAR_RecChg_Desc CHAR(31),
    @OTVTAR_Lagoon_Flag TINYINT,
    @OTVTAR_Lagoon_Amount NUMERIC(18,2),
    @OTVTAR_Lawn_Flag TINYINT,
    @OTVTAR_Lawn_Amount NUMERIC(18,2),
    @OTVTAR_Rent_Change_Date DATETIME,
    @OTVTAR_Water_Flag TINYINT,
    @OTVTAR_Water_Amount NUMERIC(18,2),
    @OTVTAR_Accept_Pay_Type SMALLINT,
    @OTVTAR_ACH_AccountNumber CHAR(21),
    @OTVTAR_ACH_BankName CHAR(31),
    @OTVTAR_ACH_Checkbox TINYINT,
    @OTVTAR_ACH_EnrollDate DATETIME,
    @OTVTAR_ACH_RentAmount NUMERIC(18,2),
    @OTVTAR_ACH_RoutingNumber CHAR(17),
    @OTVTAR_ACH_StartDate DATETIME,
    @NOTEINDX NUMERIC(18,2),
    @OTVTAR_Maintenance_Amt NUMERIC(18,2),
    @OTVTAR_Payment_Agreement TINYINT,
    @OTVTAR_Agreement_Desc CHAR(31),
    @OTVTAR_Veteran TINYINT,
    @OTVTAR_Elig_Income INT,
    @OTVTAR_DC_Number INT,
    @DEX_ROW_ID INT
)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM TAR00300_TAR_Tenant_MSTR
        WHERE OTVTAR_Program_ID = @OTVTAR_Program_ID
          AND OTVTAR_Tenant_ID = @OTVTAR_Tenant_ID
    )
    BEGIN
        RAISERROR('A record with the same Program_ID and Tenant_ID already exists.', 16, 1);
        RETURN;
    END;

    INSERT INTO TAR00300_TAR_Tenant_MSTR
    (
        OTVTAR_Tenant_Status,
        OTVTAR_Program_ID,
        OTVTAR_Tenant_ID,
        OTVTAR_App_Last_Name,
        OTVTAR_App_First_Name,
        OTVTAR_App_Middle_Name,
        OTVTAR_Cur_Name,
        OTVTAR_Cur_Address1,
        OTVTAR_Cur_Address2,
        OTVTAR_Cur_City,
        OTVTAR_Cur_CountyCode,
        OTVTAR_Cur_State,
        OTVTAR_Cur_ZipCode,
        OTVTAR_Cur_Telephone,
        OTVTAR_Perm_Name,
        OTVTAR_Perm_Address1,
        OTVTAR_Perm_Address2,
        OTVTAR_Perm_City,
        OTVTAR_Perm_State,
        OTVTAR_Perm_ZipCode,
        OTVTAR_Perm_Telephone,
        OTVTAR_Sex,
        OTVTAR_Project_ID,
        OTVTAR_Fam_Minority_Code,
        OTVTAR_Tribal_Code,
        OTVTAR_Birth_Date,
        OTVTAR_Elderly,
        OTVTAR_Disabled,
        OTVTAR_Handicapped,
        OTVTAR_HusbWife,
        OTVTAR_Family_Count,
        OTVTAR_Bedrooms,
        OTVTAR_DIB,
        OTVTAR_Marital_Status,
        OTVTAR_Dependent_Count,
        OTVTAR_VANumber,
        OTVTAR_Benefit_SSN,
        OTVTAR_Wages,
        OTVTAR_Benefits_SS,
        OTVTAR_Benefits_SSI,
        OTVTAR_Benefits_VA,
        OTVTAR_Benefits_Other,
        OTVTAR_Welfare_AFDC,
        OTVTAR_Welfare_OAA,
        OTVTAR_Welfare_AD,
        OTVTAR_Welfare_Other,
        OTVTAR_Other_Income,
        OTVTAR_Gross_Income,
        OTVTAR_Adj_Gross_Income,
        OTVTAR_Anticipated_Rent,
        OTVTAR_Recert_Date,
        OTVTAR_Empr_Name,
        OTVTAR_Empr_Address1,
        OTVTAR_Empr_Address2,
        OTVTAR_Empr_City,
        OTVTAR_Empr_State,
        OTVTAR_Empr_ZipCode,
        OTVTAR_Empr_Telephone,
        OTVTAR_Housing_Code,
        OTVTAR_Housing_Cost,
        OTVTAR_Displacement_Stat,
        OTVTAR_Credit_Verified,
        OTVTAR_Total_Assets,
        OTVTAR_Previous_Aid,
        OTVTAR_Owner_ID,
        OTVTAR_Unit_ID,
        OTVTAR_Lease_Date,
        OTVTAR_Security_Deposit,
        OTVTAR_Rent_Amount,
        OTVTAR_Number_Incomes,
        OTVTAR_Income_From_Asset,
        OTVTAR_Qualify_Low_Income,
        OTVTAR_Qualify_VeryLow_Income,
        OTVTAR_Low_Income_Code,
        OTVTAR_VeryLow_Income_Co,
        OTVTAR_MedAllowance_Amt,
        OTVTAR_TotalAllow_Amt,
        OTVTAR_Gross_Rent,
        OTVTAR_GrossRent_Cont,
        OTVTAR_HAP_Amt,
        OTVTAR_UtilitiesAllow_Am,
        OTVTAR_Net_Rent_Cont,
        OTVTAR_Cerficate_Number,
        OTVTAR_Movein_Date,
        OTVTAR_Moveout_Date,
        OTVTAR_Enumeration_Code,
        OTVTAR_Claim_Amt,
        OTVTAR_PrefPayment_Date,
        OTVTAR_LeaseSublease,
        OTVTAR_LeaseSublease_Dat,
        OTVTAR_AR_Balance,
        OTVTAR_Next_Number,
        OTVTAR_YTDUtilityAllow_A,
        OTVTAR_Admin_Fee,
        OTVTAR_Last_Number,
        OTVTAR_Contract_Number,
        OTVTAR_Security_Deposit_,
        OTVTAR_HAP_Payment_Code,
        OTVTAR_Terminated_Status,
        OTVTAR_Sec8_Ref_Number,
        OTVTAR_WO_Pending,
        OTVTAR_WO_Amount,
        OTVTAR_Security_Refund,
        OTVTAR_SecurityCheckNO,
        OTVTAR_ChargeOut_Date,
        OTVTAR_Collection_Expens,
        OTVTAR_Collection_Amount,
        OTVTAR_Collection_Orig_A,
        OTVTAR_RecChg_Flag,
        OTVTAR_RecChg_Amount,
        OTVTAR_RecChg_Acct_1,
        OTVTAR_RecChg_Acct_2,
        OTVTAR_RecChg_Acct_3,
        OTVTAR_RecChg_Acct_4,
        OTVTAR_RecChg_Acct_5,
        OTVTAR_RecChg_Desc,
        OTVTAR_Lagoon_Flag,
        OTVTAR_Lagoon_Amount,
        OTVTAR_Lawn_Flag,
        OTVTAR_Lawn_Amount,
        OTVTAR_Rent_Change_Date,
        OTVTAR_Water_Flag,
        OTVTAR_Water_Amount,
        OTVTAR_Accept_Pay_Type,
        OTVTAR_ACH_AccountNumber,
        OTVTAR_ACH_BankName,
        OTVTAR_ACH_Checkbox,
        OTVTAR_ACH_EnrollDate,
        OTVTAR_ACH_RentAmount,
        OTVTAR_ACH_RoutingNumber,
        OTVTAR_ACH_StartDate,
        NOTEINDX,
        OTVTAR_Maintenance_Amt,
        OTVTAR_Payment_Agreement,
        OTVTAR_Agreement_Desc,
        OTVTAR_Veteran,
        OTVTAR_Elig_Income,
        OTVTAR_DC_Number,
        DEX_ROW_ID
    )
    VALUES
    (
        @OTVTAR_Tenant_Status,
        @OTVTAR_Program_ID,
        @OTVTAR_Tenant_ID,
        @OTVTAR_App_Last_Name,
        @OTVTAR_App_First_Name,
        @OTVTAR_App_Middle_Name,
        @OTVTAR_Cur_Name,
        @OTVTAR_Cur_Address1,
        @OTVTAR_Cur_Address2,
        @OTVTAR_Cur_City,
        @OTVTAR_Cur_CountyCode,
        @OTVTAR_Cur_State,
        @OTVTAR_Cur_ZipCode,
        @OTVTAR_Cur_Telephone,
        @OTVTAR_Perm_Name,
        @OTVTAR_Perm_Address1,
        @OTVTAR_Perm_Address2,
        @OTVTAR_Perm_City,
        @OTVTAR_Perm_State,
        @OTVTAR_Perm_ZipCode,
        @OTVTAR_Perm_Telephone,
        @OTVTAR_Sex,
        @OTVTAR_Project_ID,
        @OTVTAR_Fam_Minority_Code,
        @OTVTAR_Tribal_Code,
        @OTVTAR_Birth_Date,
        @OTVTAR_Elderly,
        @OTVTAR_Disabled,
        @OTVTAR_Handicapped,
        @OTVTAR_HusbWife,
        @OTVTAR_Family_Count,
        @OTVTAR_Bedrooms,
        @OTVTAR_DIB,
        @OTVTAR_Marital_Status,
        @OTVTAR_Dependent_Count,
        @OTVTAR_VANumber,
        @OTVTAR_Benefit_SSN,
        @OTVTAR_Wages,
        @OTVTAR_Benefits_SS,
        @OTVTAR_Benefits_SSI,
        @OTVTAR_Benefits_VA,
        @OTVTAR_Benefits_Other,
        @OTVTAR_Welfare_AFDC,
        @OTVTAR_Welfare_OAA,
        @OTVTAR_Welfare_AD,
        @OTVTAR_Welfare_Other,
        @OTVTAR_Other_Income,
        @OTVTAR_Gross_Income,
        @OTVTAR_Adj_Gross_Income,
        @OTVTAR_Anticipated_Rent,
        @OTVTAR_Recert_Date,
        @OTVTAR_Empr_Name,
        @OTVTAR_Empr_Address1,
        @OTVTAR_Empr_Address2,
        @OTVTAR_Empr_City,
        @OTVTAR_Empr_State,
        @OTVTAR_Empr_ZipCode,
        @OTVTAR_Empr_Telephone,
        @OTVTAR_Housing_Code,
        @OTVTAR_Housing_Cost,
        @OTVTAR_Displacement_Stat,
        @OTVTAR_Credit_Verified,
        @OTVTAR_Total_Assets,
        @OTVTAR_Previous_Aid,
        @OTVTAR_Owner_ID,
        @OTVTAR_Unit_ID,
        @OTVTAR_Lease_Date,
        @OTVTAR_Security_Deposit,
        @OTVTAR_Rent_Amount,
        @OTVTAR_Number_Incomes,
        @OTVTAR_Income_From_Asset,
        @OTVTAR_Qualify_Low_Income,
        @OTVTAR_Qualify_VeryLow_Income,
        @OTVTAR_Low_Income_Code,
        @OTVTAR_VeryLow_Income_Co,
        @OTVTAR_MedAllowance_Amt,
        @OTVTAR_TotalAllow_Amt,
        @OTVTAR_Gross_Rent,
        @OTVTAR_GrossRent_Cont,
        @OTVTAR_HAP_Amt,
        @OTVTAR_UtilitiesAllow_Am,
        @OTVTAR_Net_Rent_Cont,
        @OTVTAR_Cerficate_Number,
        @OTVTAR_Movein_Date,
        @OTVTAR_Moveout_Date,
        @OTVTAR_Enumeration_Code,
        @OTVTAR_Claim_Amt,
        @OTVTAR_PrefPayment_Date,
        @OTVTAR_LeaseSublease,
        @OTVTAR_LeaseSublease_Dat,
        @OTVTAR_AR_Balance,
        @OTVTAR_Next_Number,
        @OTVTAR_YTDUtilityAllow_A,
        @OTVTAR_Admin_Fee,
        @OTVTAR_Last_Number,
        @OTVTAR_Contract_Number,
        @OTVTAR_Security_Deposit_,
        @OTVTAR_HAP_Payment_Code,
        @OTVTAR_Terminated_Status,
        @OTVTAR_Sec8_Ref_Number,
        @OTVTAR_WO_Pending,
        @OTVTAR_WO_Amount,
        @OTVTAR_Security_Refund,
        @OTVTAR_SecurityCheckNO,
        @OTVTAR_ChargeOut_Date,
        @OTVTAR_Collection_Expens,
        @OTVTAR_Collection_Amount,
        @OTVTAR_Collection_Orig_A,
        @OTVTAR_RecChg_Flag,
        @OTVTAR_RecChg_Amount,
        @OTVTAR_RecChg_Acct_1,
        @OTVTAR_RecChg_Acct_2,
        @OTVTAR_RecChg_Acct_3,
        @OTVTAR_RecChg_Acct_4,
        @OTVTAR_RecChg_Acct_5,
        @OTVTAR_RecChg_Desc,
        @OTVTAR_Lagoon_Flag,
        @OTVTAR_Lagoon_Amount,
        @OTVTAR_Lawn_Flag,
        @OTVTAR_Lawn_Amount,
        @OTVTAR_Rent_Change_Date,
        @OTVTAR_Water_Flag,
        @OTVTAR_Water_Amount,
        @OTVTAR_Accept_Pay_Type,
        @OTVTAR_ACH_AccountNumber,
        @OTVTAR_ACH_BankName,
        @OTVTAR_ACH_Checkbox,
        @OTVTAR_ACH_EnrollDate,
        @OTVTAR_ACH_RentAmount,
        @OTVTAR_ACH_RoutingNumber,
        @OTVTAR_ACH_StartDate,
        NOTEINDX,
        @OTVTAR_Maintenance_Amt,
        @OTVTAR_Payment_Agreement,
        @OTVTAR_Agreement_Desc,
        @OTVTAR_Veteran,
        @OTVTAR_Elig_Income,
        @OTVTAR_DC_Number,
        @DEX_ROW_ID
    )
END
GO
CREATE PROCEDURE sp_Select_TAR_Tenant
    @OTVTAR_Program_ID CHAR(15),
    @OTVTAR_Tenant_ID CHAR(11)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM TAR00300_TAR_Tenant_MSTR
    WHERE OTVTAR_Program_ID = @OTVTAR_Program_ID
       OR OTVTAR_Tenant_ID = @OTVTAR_Tenant_ID;
END;
GO